goals/goals/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'goals.views.home', name='home'),
    # url(r'^goals/', include('goals.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

tutorin/app/accounts/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('accounts.views',
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^login/$', 'login', {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^logout/$', 'logout', {'template_name': 'accounts/logout.html'}, name="logout"),
    url(r'^register/$', 'register', {'template_name': 'accounts/register.html'}, name="register"),
)

tutorin/app/bookings/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import patterns, include, url

urlpatterns = patterns('bookings.views',
    url(r'^order/$', 'order', name='order'),
)

tutorin/app/main/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),
    url(r'^s/$', 'search', name='search'),
)

tutorin/app/tutors/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('tutors.views',
    url(r'^profile/$', 'profile', name='profile'),
    url(r'^(?P<slug>.+)/$', 'details', name='details'),
)

tutorin/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from filebrowser.sites import site as file_browser_site
from django.conf import settings

from api import router

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/filebrowser/', include(file_browser_site.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^router/$', router, name='router'),
    url(r'^router/api/$', router.api, name='api'),
    url(r'^accounts/', include('app.accounts.urls', namespace="accounts")),
    url(r'^tutors/', include('app.tutors.urls', namespace="tutors")),
    url(r'^students/', include('app.students.urls', namespace="students")),
    url(r'^bookings/', include('app.bookings.urls', namespace="bookings")),
    url(r'', include('app.main.urls', namespace="main")),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:],'django.views.static.serve',{'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

tutorin/app/main/forms.py
# -*- encoding: utf-8 -*-
__author__ = 'maxim'

from django.core.urlresolvers import reverse
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Button, Submit
from crispy_forms.bootstrap import FormActions, PrependedText

class CrispySearchForm(forms.Form):

    def __init__(self, *args, **kwargs):

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = reverse("main:search")
        self.helper.layout = Layout(
            'username',
            'password',
            FormActions(
                Submit('login', 'Login'),
            )
        )

tutorin/app/main/views.py
# -*- encoding: utf-8 -*-

from django.db.models import Q
from django.utils import timezone as dj_timezone

from util.decorators import render_to
from util.gmap import Location
from datetime import date, datetime, timedelta

from app.tutors.models import Tutor, Slot
from app.bookings.models import Order
from app.util import timezone

from hashlib import md5

tz = dj_timezone.get_current_timezone()
DEFAULT_RANGE_IN_MILES = 200


@render_to("main/index.html")
def index(request):
    return {
        'categories': "lorem ipsum dolor sit amet consectetur adipiscing elit Donec id justo mauris".split(" "),
        'tutors': ['Shaimaa', 'Fatma', 'Maha', 'Reem', 'Farida', 'Aya', 'Shahd', 'Ashraqat', 'Sahar', 'Fatin', 'Dalal', 'Doha', 'Fajr']
    }

@render_to("main/search.html")
def search(request):
    if request.method == 'POST':
        Order.check_expired()
        location = request.POST.get('location')
        subject = request.POST.get('subject')
        ds = request.POST.get('date')

        filters = {'bookings__isnull': True}

        if ds:
            try:
                dt = datetime.strptime(ds,"%d-%m-%Y").replace(tzinfo=tz)
            except:
                filters.update({"start__gt": timezone.today()})
            else:
                de = dt + timedelta(days=1)
                filters.update({"start__lte": de, "end__gte": dt})
        else:
            filters.update({"start__gt": timezone.today()})

        if subject:
            filters.update({"tutor__subjects__name__exact": subject})

        if location:
            loc = Location()
            loc.address = unicode(location)
            tutors_in_range = Tutor.objects.by_prox(loc, DEFAULT_RANGE_IN_MILES)
            slots = Slot.objects.filter(Q(tutor__in=tutors_in_range)&Q(**filters))
        else:
            slots = Slot.objects.filter(**filters)

        return {
            'slots': slots,
        }

    else:
        return {}

tutorin/app/main/templates/main/base.html
<!DOCTYPE HTML>{% load static from staticfiles %}{% load components %}
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery.countdown.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.7.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.util.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.rpc.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax-csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% url 'api' %}"></script>
    {% block extrahead %}{% endblock %}
</head>
<body>
<div class="container">
    <div class="row header">
        {% block header %}
            <div class="span3 ">
                {% block branding %}
                    <a href="{% url 'main:index' %}" class="logo">
                        <span class="title">Tutor-in</span>
                        <span class="subtitle">Tutors engine</span>
                    </a>
                {% endblock %}
            </div>
            <div class="span9">
                <div class="top-menu">
                    {% block mainmenu %}
                        {% if request.user.is_anonymous %}
                        <a href="#" class="btn">Take a Tour</a>
                        <a href="{% url "accounts:register" %}" class="btn">Sign Up</a>
                        <a href="{% url "accounts:login" %}" class="btn">Sign In</a>
                        {% else %}
                        <div class="top-menu">
                        {# TODO replace request.user.username with user.get_profile.fullname when all profile types will be ready #}
                        {% active_order %}
			            <span class="tutor-name"><a href="{% url "accounts:profile" %}">{{ request.user.username }}</a></span>
                        <a href="{% url "accounts:logout" %}" class="btn">Sign Out</a>
		                </div>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        {% endblock %}
    </div>

    <div class="row wrapper">
        {% block content %}
        {% endblock %}
    </div>

    <div class="row footer">
        {% block footer %}
            <div class="span12">
                <div class="copy well">Footer</div>
            </div>
        {% endblock %}
    </div>

</div>
{% block modals %}{% endblock %}
{% block scripting %}{% endblock %}
</body>
</html>

tutorin/app/main/templates/main/index.html
{% extends "main/base.html" %}{% load static from staticfiles %}
{% load components %}
{% block extrahead %}
    {{ super }}
    <link rel="stylesheet" href="{% static "css/datepicker.css" %}" />
    <script type="text/javascript" src="{% static "js/bootstrap-datepicker.js" %}"></script>
{% endblock %}
{% block content %}

    <div class="span12">
        {% include "main/blocks/carousel.html" %}
    </div>

    {% slot_search %}

    <div class="span12">
        <div class="categiries-gallery">
            <h2 class="title">Categories</h2>
            <ul class="thumbnails">
                {% for category in categories %}
                    <li class="span3">
                        <a href="#" class="thumbnail">
                            <img src="" alt="">
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="span12">
        <div class="tutors-gallery">
            <h2 class="title">Tutors</h2>
            <ul class="thumbnails">
                {% for tutor in tutors %}
                    <li class="span3">
                        <a href="#" class="thumbnail">
                            <img src="" alt="">
				    <span class="thumbnail-popover">
                    {{ tutor }}<br/>
					Extra information on tutor
				    </span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>


{% endblock %}

{% block scripting %}
    {{ super }}
    <script type="text/javascript">
        $(document).ready(function () {
            var dp = $('.datepicker');
            dp.datepicker();
        });
    </script>
{% endblock %}

tutorin/app/main/templates/main/search.html
{% extends "main/base.html" %}{% load static from staticfiles %}
{% load components %}
{% block extrahead %}
    {{ super }}
    <link rel="stylesheet" href="{% static "css/datepicker.css" %}"/>
    <script type="text/javascript" src="{% static "js/bootstrap-datepicker.js" %}"></script>
{% endblock %}
{% block content %}

    <div class="span12">
        {% include "main/blocks/carousel.html" %}
    </div>

    {% slot_search %}

    <div class="span12">
        <div class="search-results">
            <h2 class="title">Search results</h2>
            <ul class="thumbnails">
                {% for slot in slots %}
                    <li class="span12">
                        <a href="#" class="thumbnail make-booking-js" data-slot-id="{{ slot.id }}"
                           data-slot-online="{{ slot.is_online }}" data-slot-home="{{ slot.is_home }}" data-slot-away="{{ slot.is_away }}">
                            <p>{{ slot.tutor }}</p>
                            <p>{{ slot.start }} - {{ slot.end }}</p>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock %}

{% block modals %}
    {{ super }}
    <div class="modal hide fade booking-type" id="booking-type-modal" style="text-align: left;">
	    <div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h3>Choose type of slot</h3>
	    </div>
		<div class="modal-footer">
		    <button class="btn btn-default booking-type-js" id="booking-type-online-js" data-type='0' title="Online">Online</button>
		    <button class="btn btn-default booking-type-js" id="booking-type-home-js" data-type='1' title="At home">At home</button>
		    <button class="btn btn-default booking-type-js" id="booking-type-away-js" data-type='2' title="Away">Away</button>
            <button class="btn btn-danger" id="cancel-booking-js" title="Cancel">Cancel</button>
		</div>
	</div>

{% endblock %}

{% block scripting %}
    {{ super }}
    <script type="text/javascript">
        $(document).ready(function () {
            var dp = $('.datepicker');
            var modal = $("#booking-type-modal");
            var slot_id = null;
            dp.datepicker();

            $(".make-booking-js").on('click', function(e) {
                e.preventDefault();
                slot_id = $(this).data('slot-id');
                if($(this).data('slot-online')=="True") {
                    $("#booking-type-online-js").removeAttr("disabled");
                } else {
                    $("#booking-type-online-js").attr("disabled","disabled");
                }
                if($(this).data('slot-home')=="True") {
                    $("#booking-type-home-js").removeAttr("disabled");
                } else {
                    $("#booking-type-home-js").attr("disabled","disabled");
                }
                if($(this).data('slot-away')=="True") {
                    $("#booking-type-away-js").removeAttr("disabled");
                } else {
                    $("#booking-type-away-js").attr("disabled","disabled");
                }

                modal.modal('show');

            });
            $(".booking-type-js").on('click', function() {
                var slot_type = $(this).data('type');
                BookingApi.order_create(slot_id, slot_type, function(response) {
                    if(response.success) {
                        if (response.anonymous) {
                            window.location.replace("{% url "accounts:login" %}?next={% url "bookings:order" %}");
                        } else {
                            window.location.replace("{% url "bookings:order" %}");
                        }
                    } else {
                        alert(response.msg)
                    }
                });
            })

            $("#cancel-booking-js").on('click', function() {
                modal.modal('hide');
            })
        });
    </script>
{% endblock %}